### ISSUE TITLE
关于README的一点点小的疑问

### ISSUE THREAD

**Issue by ncs19960831** [MoeLoli/Comment2Telegram#1]
#我按照README进行安装之后可以在服务器正常看到插件，但是我无法进行使用，因为我点击启用的时候服务器会回复我错误500且没有任何错误代码。
我文件名字修改过了，甚至改成了和其他可以正常使用的插件一样的所有者，可以依然无法使用。
希望你能够给我一些帮助
万分感谢。

**Comment by Adoream** [comment]
可以给我发一下你的Typecho的环境吗。。

**Comment by rstorz** [comment]
可以的话麻烦顺便再提供一下你的服务器商家 机房 还有机器上的LNMP环境吧orz

**Comment by StarryFK** [comment]
我测试了一下，，其实问题很简单：
**为什么要修改插件目录名为**`Comment2Typecho`
实际上目录名就按照插件原来的名字`Comment2Telegram`就好了。。
README的指引改一下就好惹_(:3]<)_

**Comment by Adoream** [comment]
@StarryFK 已经修复了这个智障的错误。。
