### ISSUE TITLE
设置 bot 回调失败

### ISSUE THREAD

**Issue by zsakvo** [MoeLoli/Comment2Telegram#2]
在填写好 Token 以及 MasterID 并保存以后，重新进入插件设置界面，点击设置 bot 回调，按钮长时间处于灰色并且无任何返回信息。经过抓包后发现得到了` 302 Moved Temporarily `，请问该如何解决？（插件是直接从此仓库克隆到 vps 的）

**Comment by Adoream** [comment]
能否提供一下后台的截图？

**Comment by zsakvo** [comment]
![image](https://user-images.githubusercontent.com/25399519/53690570-2a00b400-3da8-11e9-88d1-b32df136b93f.png)

![image](https://user-images.githubusercontent.com/25399519/53690576-3ab12a00-3da8-11e9-9d3f-c4b9a9538e20.png)

尝试过禁用 CommentFilter 插件，但是依旧是一直没有响应。

![image](https://user-images.githubusercontent.com/25399519/53690586-7c41d500-3da8-11e9-99dd-3d89e301a6a8.png)

抓包截图

**Comment by Adoream** [comment]
感觉302有可能是你nginx配置的问题吧。。我还有一个月就要小高考了。。可能没什么时间来折腾这些。。

**Comment by zsakvo** [comment]
行，那我再看看吧，考试加油
