### ISSUE TITLE
无法设置 bot 回调

### ISSUE THREAD

**Issue by vcheckzen** [MoeLoli/Comment2Telegram#3]
显示 `失败：Not Found`

**Comment by Adoream** [comment]
请问有先保存再设置嘛？

**Comment by Adoream** [comment]
你现在可以尝试使用最新的发现包进行尝试

**Comment by vcheckzen** [comment]
现在可以设置，但仍然无法推送，设置界面有一个异常，使用的是 `PHP Version 7.2.4`。
![2Q_PG_PA@V2GW56B65T~(J8](https://user-images.githubusercontent.com/18008498/61259545-41679900-a7ad-11e9-8bce-4731b05364c7.png)

**Comment by Adoream** [comment]
好了已经更新

**Comment by vcheckzen** [comment]
大佬辛苦了，点保存设置没有发生异常，可我不知道为什么还是不推送，`Token` 跟 `MasterID` 应该没问题
![}O {JK~C %@J`%JZ@@@0Y7A](https://user-images.githubusercontent.com/18008498/61290608-dba3fd00-a7fe-11e9-8ac1-7638413cf7c2.png)
![JTD@YWL$ UIMFHKRG% Q} 7](https://user-images.githubusercontent.com/18008498/61290615-dd6dc080-a7fe-11e9-8fe7-c6b0de5dc3a4.png)

**Comment by Adoream** [comment]
哪里的服务器啊？...

**Comment by vcheckzen** [comment]
阿里的香港轻量云

**Comment by Adoream** [comment]
@vcheckzen 那也不会是连接不上的问题。。你评论以后页面里会有什么提醒？

**Comment by vcheckzen** [comment]
页面只是评论成功，没有其他提醒。

**Comment by vcheckzen** [comment]
已经可以了，感谢大佬。我手动请求 `api` 返回会话不存在，之后发了条消息给机器人再请求就正常了，插件也是正常的，大佬可以在 `README` 里提一句。

```bash
$ curl "https://api.telegram.org/botTOKEN/sendMessage?chat_id=MasterID&text=测试"
{"ok":false,"error_code":400,"description":"Bad Request: chat not found"}
```
