### ISSUE TITLE
插件反激活逻辑有问题

### ISSUE THREAD

**Issue by if1y** [MoeLoli/Comment2Telegram#6]
这个槽点略大……

> 大概十天前我试用了本插件，综合考虑最后还是采用了 Server酱 推送得到方式，于是理所当然地把插件禁用、删除。
> 直到今天翻了下访问记录，才发现一直有个 IP 高频反复访问 `/action/CommentEdit?do=CallBack`，足足跑了近7000条，多多少少对性能和流量有一定影响
> 第一反应是被吓到了，看路径以为是渗透爬虫，后来查 IP 归属地发现是 Telegram 的节点，综合考虑、验证才确定是本插件的问题，然后手动执行了 `/deleteWebhook` 得以解决

**总之， 创建了东西不删干净真的太那啥了……
真诚建议完善反激活逻辑**

**Comment by MoeLoli** [comment]
@yesmiley 您可以提交一个 PR 到仓库
还是手头都是课题的原因这段时间并没有多少时间能来维护
